

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  package

    - name: Run Shell Commands
      run: |
        trivy fs --format table -o trivy.report .

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        args: >
          -Dsonar.host.url=${{secrets.SONAR_URL}}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=Boardgame
          -Dsonar.projectName=Boardgame
          -Dsonar.java.binaries=.
